from datetime import datetime
from dateutil.relativedelta import relativedelta

NEWS_API_KEY = "612a7281b32f4a9abf0edc18aae5effd"
ALPHA_VANTAGE_API_KEY = "W2653K1FAP713260"

# Dynamic start date → Last 10 years
today = datetime.today()

START_DATE = (
    today - relativedelta(years=10)
).strftime("%Y-%m-%d")

MODEL_FILE = "stock_model.pkl"
ACCURACY_FILE = "model_accuracy.pkl"
TOP_STOCKS_CACHE_FILE = "top_3_stocks_cache.pkl"
NSE_STOCK_MASTER = "data/nse_stock_master.csv"
NIFTY_50_DATA = "data/nifty_50.csv"
PORTFOLIO = "data/portfolio.csv"
DATA_FOLDER = "data"

PORTFOLIO_ADVISOR = "pages/portfolio_advisor.py"
MANAGE_PORTFOLIO = "pages/manage_portfolio.py"

TRAINING_STOCKS = [
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "INFY.NS",
    "ICICIBANK.NS",
    "HINDUNILVR.NS",
    "ITC.NS",
    "SBIN.NS",
    "BHARTIARTL.NS",
    "LT.NS",
    "KOTAKBANK.NS",
    "AXISBANK.NS",
    "ASIANPAINT.NS",
    "MARUTI.NS",
    "SUNPHARMA.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "BAJFINANCE.NS",
    "NESTLEIND.NS",
    "WIPRO.NS",
    "TECHM.NS",
    "POWERGRID.NS",
    "NTPC.NS",
    "ONGC.NS",
    "JSWSTEEL.NS",
    "HCLTECH.NS",
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "COALINDIA.NS",
    "BPCL.NS",
    "IOC.NS",
    "DIVISLAB.NS",
    "BAJAJFINSV.NS",
    "BAJAJ-AUTO.NS",
    "HINDALCO.NS",
    "GRASIM.NS",
    "EICHERMOT.NS",
    "DRREDDY.NS",
    "CIPLA.NS",
    "APOLLOHOSP.NS",
    "BRITANNIA.NS",
    "HEROMOTOCO.NS",
    "SHREECEM.NS",
    "INDUSINDBK.NS",
    "TATASTEEL.NS",
    "UPL.NS",
    "M&M.NS",
    "SBILIFE.NS",
    "HDFCLIFE.NS",
    "DLF.NS",
    "PIDILITIND.NS",
    "DABUR.NS",
    "AMBUJACEM.NS",
    "GODREJCP.NS",
    "SIEMENS.NS",
    "BOSCHLTD.NS",
    "COLPAL.NS",
    "LUPIN.NS",
    "AUROPHARMA.NS",
    "BERGEPAINT.NS",
    "PAGEIND.NS",
    "MUTHOOTFIN.NS",
    "TORNTPHARM.NS",
    "VEDL.NS",
    "CANBK.NS",
    "BANKBARODA.NS",
    "PNB.NS",
    "IDFCFIRSTB.NS",
    "FEDERALBNK.NS",
    "BANDHANBNK.NS",
    "YESBANK.NS",
    "INDIGO.NS",
    "IRCTC.NS",
    "PAYTM.NS",
    "NAUKRI.NS",
    "POLYCAB.NS",
    "HAVELLS.NS",
    "VOLTAS.NS",
    "ABB.NS",
    "CUMMINSIND.NS",
    "AUBANK.NS",
    "TRENT.NS",
    "TATAPOWER.NS",
    "ADANIGREEN.NS",
    "ADANIPOWER.NS",
    "GAIL.NS",
    "PETRONET.NS",
    "SAIL.NS",
    "NMDC.NS",
    "JINDALSTEL.NS",
    "HINDZINC.NS",
    "SRF.NS",
    "PIIND.NS",
    "DEEPAKNTR.NS",
    "ALKEM.NS",
    "GLAND.NS",
    "BIOCON.NS",
    "ABBOTINDIA.NS",
    "MAXHEALTH.NS",
    "FORTIS.NS",
    "LALPATHLAB.NS",
    "METROPOLIS.NS",
    "MFSL.NS",
    "CHOLAFIN.NS",
    "PFC.NS",
    "RECLTD.NS",
    "LICHSGFIN.NS",
    "MPHASIS.NS",
    "COFORGE.NS",
    "PERSISTENT.NS",
    "LTIM.NS",
    "LTTS.NS",
    "KPITTECH.NS",
    "TATAELXSI.NS",
    "BHEL.NS",
    "BEL.NS",
    "HAL.NS",
    "CONCOR.NS",
    "ASHOKLEY.NS",
    "ESCORTS.NS",
    "TVSMOTOR.NS",
    "EXIDEIND.NS",
    "MOTHERSON.NS",
    "BALKRISIND.NS",
    "ACC.NS",
    "RAMCOCEM.NS",
    "JKCEMENT.NS",
    "OBEROIRLTY.NS",
    "GODREJPROP.NS",
    "LODHA.NS",
    "PHOENIXLTD.NS",
    "INDHOTEL.NS",
    "LEMONTREE.NS",
    "JUBLFOOD.NS",
    "DMART.NS",
    "SHOPERSTOP.NS",
    "TATACONSUM.NS",
    "MARICO.NS",
    "UBL.NS",
    "EMAMILTD.NS",
    "PATANJALI.NS",
    "BATAINDIA.NS",
    "RELAXO.NS",
    "VIPIND.NS",
    "CROMPTON.NS",
    "WHIRLPOOL.NS",
    "ASTRAL.NS",
    "FINCABLES.NS",
    "SUPREMEIND.NS",
    "COROMANDEL.NS",
    "CHAMBLFERT.NS",
    "GNFC.NS",
    "RALLIS.NS",
    "TATACHEM.NS",
    "NAVINFLUOR.NS",
    "AARTIIND.NS",
    "ATUL.NS",
    "CLEAN.NS",
    "SOLARINDS.NS",
    "IRFC.NS",
    "RVNL.NS",
    "NBCC.NS",
    "HUDCO.NS",
    "NCC.NS",
    "KEC.NS",
    "LTFOODS.NS",
    "SONACOMS.NS",
    "SUPRAJIT.NS",
    "SKFINDIA.NS",
    "RITES.NS",
    "ANGELONE.NS",
    "CDSL.NS",
    "BSE.NS",
    "MCX.NS",
    "CAMS.NS",
    "IEX.NS",
    "ROUTE.NS",
    "EASEMYTRIP.NS",
    "DEVYANI.NS",
    "KALYANKJIL.NS",
    "SAPPHIRE.NS",
    "NYKAA.NS",
    "POLICYBZR.NS",
    "DELHIVERY.NS",
    "CAMPUS.NS"
]